<?php

namespace OML\TypingTestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestTakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestTakerRepository extends EntityRepository
{
}
